### ISSUE TITLE
Rename to VogelsSprekelerEtAl2011?

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/VogelsSprekelerEtAl2011#6]
@pgleeson would it be OK if I renamed the repo to VogelsSprekelerEtAl2011? They contributed equally to the work (and I've therefore[ named the STDP rule vogels-sprekeler in NEST too](https://github.com/nest/nest-simulator/blob/master/models/vogels_sprekeler_connection.h)).

**Comment by pgleeson** [comment]
Ok, @sanjayankur31, if you know them and think that's a better name I can rename this. GitHub is pretty good at redirecting to renamed repos, so it shouldn't affect anyone who's cloned it in the past. 

Note, the OSB project will still be http://www.opensourcebrain.org/projects/vogelsetal2011, it's more difficult to rename those. However the title can be changed too. It will still point to https://github.com/OpenSourceBrain/VogelsEtAl2011, but will hopefully redirect when it's used on OSB.

Is your code in https://github.com/OpenSourceBrain/VogelsEtAl2011/pull/4 still working with the master branch (or development) of Auryn (apologies for letting this slide)?

**Comment by sanjayankur31** [comment]
> Ok, @sanjayankur31, if you know them and think that's a better name I can rename this. GitHub is pretty good at redirecting to renamed repos, so it shouldn't affect anyone who's cloned it in the past.

It shouldn't - yea. The paper says that they contributed equally, so I just thought it'd be the right thing to do to give them equal credit :)

> Note, the OSB project will still be http://www.opensourcebrain.org/projects/vogelsetal2011, it's more difficult to rename those. However the title can be changed too. It will still point to https://github.com/OpenSourceBrain/VogelsEtAl2011, but will hopefully redirect when it's used on OSB.

> Is your code in #4 still working with the master branch (or development) of Auryn (apologies for letting this slide)?

I'll have to check - I moved to NEST quite a while ago, and I think Auryn's changed a bit too since then. I have the model replicated in NEST, but I need to generate the exact graphs showing the patterns. It's been on my TODO list for a bit, but I've been caught up in other research :(

I can rerun the auryn simulation to see if it works sometime next week and let you know, to begin with.

**Comment by pgleeson** [comment]
Ok, renamed!

@janfb let me know if you have any problem with your fork.
